INSERT INTO tb_employee(name, email, password, salary) VALUES ('Ana', 'ana@email.com', '12345', 1200.00)
INSERT INTO tb_employee(name, email, password, salary) VALUES ('Bia', 'bia@email.com', 'tetrt', 1240.00)
INSERT INTO tb_employee(name, email, password, salary) VALUES ('Carlos', 'car@email.com', 'sfdsfs', 1245.00)
INSERT INTO tb_employee(name, email, password, salary) VALUES ('Daniel', 'dan@email.com', 'try456', 12234.00)
INSERT INTO tb_employee(name, email, password, salary) VALUES ('Eduardo', 'ed@email.com', 'fdgdfg', 1243.00)